name: General Bug Report
description: File a general bug report
title: "[Bug]: "
labels: ["triage"]
assignees:
  - refringe
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to fill out a bug report!
  - type: input
    id: discord-username
    attributes:
      label: Discord Username
      description: If we need more information, can we contact you on the SPT discord? What's your username?
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: SPT Version
      description: What version of SPT are you running?
      options:
        - 3.5.0
        - 3.4.1
        - 3.4.0
        - 3.3.0
        - 3.2.5
        - 3.2.4
        - 3.2.3
        - 3.2.2
        - 3.2.1
        - 3.2.0
        - 3.1.1
        - 3.1.0
        - 3.0.0
    validations:
      required: true
  - type: textarea
    id: server-log
    attributes:
      label: Server Log
      description: Please paste your entire server log into this input. Be sure to include the beginning where all of your mods, and mod versions, are loaded/listed.
      render: shell
    validations:
      required: true
